name: kyleisom.net
description: Yet Another Programming Blog
url: http://kyleisom.net
markdown: redcarpet
lsi: true
source: source
permalink: /blog/:year/:month/:day/:title
pygments: true
exclude: ["mkfile"]
redcarpet:
  extensions: ["fenced_code_blocks"]
