.Dd May 29, 2012
.Dt "KYLE ISOM" 7 PS1
.Os "Resume"
.Sh NAME
.Nm "Kyle Isom"
.Nd software security engineer
.Sh SYNOPSIS
.Bl -tag -width .Ds -compact
.It Lk http://www.kyleisom.net "Personal Site"
.It Email: Mt kyle@kyleisom.net
.El
.Sh SKILLS
.Bl -dash -width .Ds -compact
.It 
Development: C, Python, Clojure, Objective-C, UNIX / POSIX programming, 
network programming, security engineering
.It 
Software Engineering: GNU Autotools suite, LaTeX, Texinfo, mandoc
.It 
Development Tools: Valgrind, lint, rats, vim, emacs
.It 
Development Cycle: I know how to do the other engineering involved with 
software projects, such as documentation, build system setup, and developing
useful unit tests.
.It 
Security: I have a strong background in computer security, particularly the
field of secure programming. Some of my security skills include
penetration testing, reverse engineering, and proactive network
defense.
.El
.Sh WORK EXPERIENCE
.Bl -tag -width .Ds -compact
.It Echostar Technologies, L.L.C. (Englewood, CO / Software Security Engineer)
.Bl -dash -width .Ds -compact
.It
July 2010 - Present
.It
Conduct code reviews and audits in C and C++.
.It
Patch Linux kernel for embedded devices to address site-specific security 
requirements.
.It
Write Python code to generate encrypted software updates for Linux-based set 
top boxes.
.El
.El
.Sh SELECTED PROJECTS AND PUBLICATIONS
.Bl -tag -width .Ds -compact
.It Crypto Intro (Python)
.Bl -dash -width .Ds -compact
.It
An introduction to Cryptography with PyCrypto
.It
Published June 2011   
.It
Introduces cryptography to developers who may not have a solid
understanding of not only what cryptography is, but also when to use
it.
.It
Uses Python to clearly introduce how to properly integrate
cryptography into projects.
.El
.It Woofs (Python)
.Bl -dash -width .Ds -compact
.It
.Lk http://www.github.com/kisom/woofs/ "Woofs GitHub page."
.It
Share files easily from the commandline.
.It
Published July 2011
.It
Designed to quickly share a file over HTTPS.
.It
Addresses the fact that similar programs were not using TLS/SSL.
.El
.It srvwd (C)
.Bl -dash -width .Ds -compact
.It
.Lk http://www.tyrfingr.is/projects/srvwd/ "srvwd homepage."
.It
Serve Working Directory
.It
Minimal web server written in ANSI C.
.It
Serves the current working directory
.It
Forking webserver that can be chrooted for security.
.It
Designed to specifically facilitate rapid testing of statically-generated 
sites.
.El
.It FlexArgs (Objective-C)
.Bl -dash -width .Ds -compact
.It
.Lk https://github.com/kisom/flexargs "Github page."
.It
Flexible parse command line options.
.El
.El
.Sh SEE ALSO
.Bl -tag -width .Ds -compact
.It Lk https://github.com/kisom/ "Github profile."
.It Lk https://bitbucket.org/kisom/ "Bitbucket profile."
.It Lk https://www.tyrfingr.is "Unix and C coding portfolio."
.El
